// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'done': string;
  'list': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
