// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'help': string;
  'img': string;
  'loading': string;
  'search': string;
}
export const cssExports: CssExports;
export default cssExports;
