// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'toast': string;
  'toastEnter': string;
  'toastEnterDone': string;
  'toastExit': string;
  'toastExitActive': string;
  'toastText': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
