// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'back': string;
  'deleteButton': string;
  'dummyInput': string;
  'inputList': string;
  'inputWrapper': string;
  'next': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
