// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkAfter': string;
  'checkBefore': string;
  'current': string;
  'description': string;
  'done': string;
  'item': string;
  'line': string;
  'next': string;
  'prev': string;
  'step': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
