// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'correct': string;
  'error': string;
  'initialSetting': string;
  'normal': string;
}
export const cssExports: CssExports;
export default cssExports;
