// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'correct': string;
  'default': string;
  'error': string;
  'normal': string;
  'search': string;
  'searchIcon': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
