// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'help': string;
  'initialSettingsIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
