// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base': string;
  'green': string;
  'large': string;
  'medium': string;
  'red': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
