// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'close': string;
  'open': string;
  'searchBox': string;
  'searchInput': string;
  'selected': string;
  'selecterWrapper': string;
  'unselect': string;
  'userList': string;
  'userListItem': string;
}
export const cssExports: CssExports;
export default cssExports;
