// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorMessage': string;
  'initialSetting': string;
  'validateError': string;
  'validateOk': string;
}
export const cssExports: CssExports;
export default cssExports;
